# COMP8685 Deep Learning Assignment 3 (A3)

Individual (25% of total mark)

##  Task: 
You are required to develop a phyton code with additional comments to answer the question in the next section. 

##  Description: 
Create a code, in the provided template in Moodle, to train two Recurrent Neural Networks (RNNs) on the public benchmark dataset named Poker Hand available at: https://archive.ics.uci.edu/ml/datasets/Poker+Hand. 

Poker Hand dataset is composed of one training set named “poker-hand-training-true.data” and one testing set named “poker-hand-testing.data”. 
You will need to download both training and testing sets into your local disk by clicking the Data Folder link (see the image below).

In Poker Hand dataset, each data sample (row) is an example of a hand consisting of five playing cards drawn from a standard deck of 52. Each card is described using two attributes (suit and rank), for a total of 10 predictive attributes. There is one Class attribute that describes the "Poker Hand". You can find more information about this dataset from: 
https://www.kaggle.com/datasets/rasvob/uci-poker-hand-dataset

The dataset should be imported in the code. An example on how to import the dataset to your code can be found from the link below:
https://www.kaggle.com/code/rasvob/uci-poker-dataset-classification

Note: This is only a template. You can add more code/text cells if necessary.

## Imports

In [1]:
import pandas as pd
import numpy as np
import tensorflow
from tensorflow import keras
from keras.models import Sequential
from keras.layers import Dense, SimpleRNN, LSTM, CategoryEncoding
from sklearn.metrics import confusion_matrix

2023-03-24 22:19:56.922913: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2023-03-24 22:19:56.922968: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.


## Import the training and testing set in the cell below (10 marks)

In [2]:
# your code here

# read the train data
training = pd.read_csv('Data/poker-hand-training-true.data', sep=',', header=None)
training.columns = ['S1', 'C1','S2', 'C2','S3', 'C3','S4', 'C4','S5', 'C5','Label']

# read the test data
testing = pd.read_csv('Data/poker-hand-testing.data', sep=',', header=None)
testing.columns = ['S1', 'C1','S2', 'C2','S3', 'C3','S4', 'C4','S5', 'C5','Label']

# seperate the train and test data from labels
X_train, y_train = np.array(training.iloc[:,:-1]), np.array(training.iloc[:,-1])
X_test, y_test = np.array(testing.iloc[:,:-1]), np.array(testing.iloc[:,-1])

# print the shape of train and test data
print("Shape of X_train: {}".format(X_train.shape))
print("Shape of y_train: {}".format(y_train.shape))

print("Shape of X_test: {}".format(X_test.shape))
print("Shape of y_test: {}".format(y_test.shape))

Shape of X_train: (25010, 10)
Shape of y_train: (25010,)
Shape of X_test: (1000000, 10)
Shape of y_test: (1000000,)


## Implement the vanilla RNN in the cell below (10 marks)

In [3]:
# your code here
# define model architecture

model = Sequential() # create a sequential model

model.add(SimpleRNN(units=100, input_shape=(10,1), activation='tanh', return_sequences=True))  # add recurrent neurons to the model
model.add(SimpleRNN(units=150, activation='tanh', return_sequences=True))  # add recurrent neurons to the model
model.add(SimpleRNN(units=100, activation='tanh', return_sequences=True)) 
model.add(SimpleRNN(units=50, activation='tanh'))

model.add(Dense(units=10, activation='tanh')) # add dense layer as the output layer of the model

model.compile(loss='mean_squared_error', optimizer='adam', metrics=['accuracy'])

# print model summary
print(model.summary())

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 simple_rnn (SimpleRNN)      (None, 10, 100)           10200     
                                                                 
 simple_rnn_1 (SimpleRNN)    (None, 10, 150)           37650     
                                                                 
 simple_rnn_2 (SimpleRNN)    (None, 10, 100)           25100     
                                                                 
 simple_rnn_3 (SimpleRNN)    (None, 50)                7550      
                                                                 
 dense (Dense)               (None, 10)                510       
                                                                 
Total params: 81,010
Trainable params: 81,010
Non-trainable params: 0
_________________________________________________________________
None


2023-03-24 22:20:00.783215: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2023-03-24 22:20:00.783248: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
2023-03-24 22:20:00.783265: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (jupyter): /proc/driver/nvidia/version does not exist
2023-03-24 22:20:00.783495: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


## Train the vanilla RNN based on the training set in the cell below (5 marks)

In [4]:
# your code here
encoder=CategoryEncoding(num_tokens=10, output_mode="one_hot") # one hot coding to vectorize the labels
model.fit(X_train, encoder(y_train), epochs=30, batch_size=128, verbose=2)

Epoch 1/30
196/196 - 5s - loss: 0.0644 - accuracy: 0.4976 - 5s/epoch - 27ms/step
Epoch 2/30
196/196 - 3s - loss: 0.0568 - accuracy: 0.5182 - 3s/epoch - 17ms/step
Epoch 3/30
196/196 - 3s - loss: 0.0563 - accuracy: 0.5281 - 3s/epoch - 17ms/step
Epoch 4/30
196/196 - 3s - loss: 0.0561 - accuracy: 0.5312 - 3s/epoch - 17ms/step
Epoch 5/30
196/196 - 3s - loss: 0.0559 - accuracy: 0.5347 - 3s/epoch - 17ms/step
Epoch 6/30
196/196 - 3s - loss: 0.0557 - accuracy: 0.5363 - 3s/epoch - 17ms/step
Epoch 7/30
196/196 - 3s - loss: 0.0557 - accuracy: 0.5361 - 3s/epoch - 17ms/step
Epoch 8/30
196/196 - 3s - loss: 0.0555 - accuracy: 0.5386 - 3s/epoch - 17ms/step
Epoch 9/30
196/196 - 3s - loss: 0.0554 - accuracy: 0.5413 - 3s/epoch - 18ms/step
Epoch 10/30
196/196 - 3s - loss: 0.0554 - accuracy: 0.5442 - 3s/epoch - 17ms/step
Epoch 11/30
196/196 - 3s - loss: 0.0548 - accuracy: 0.5520 - 3s/epoch - 17ms/step
Epoch 12/30
196/196 - 3s - loss: 0.0548 - accuracy: 0.5529 - 3s/epoch - 18ms/step
Epoch 13/30
196/196 - 3s 

## Evaluate the vanilla RNN based on the testing set in the cell below (5 marks)

In [5]:
# your code here

# get predictions for test data and use argmax to convert output vector to labels
y_pred = np.argmax(model.predict(X_test), axis=1)

## Present the classification accuracy and confusion matrix of the vanilla RNN in the cell below (10 marks)

In [6]:
# your code here

print(confusion_matrix(y_test, y_pred))

[[451984  49225      0      0      0      0      0      0      0      0]
 [194735 227304      0    459      0      0      0      0      0      0]
 [  6947  39748      5    922      0      0      0      0      0      0]
 [  3567  15803      4   1747      0      0      0      0      0      0]
 [   566   3319      0      0      0      0      0      0      0      0]
 [  1817    179      0      0      0      0      0      0      0      0]
 [    14   1163      5    242      0      0      0      0      0      0]
 [     1    127      0    102      0      0      0      0      0      0]
 [     0     12      0      0      0      0      0      0      0      0]
 [     0      3      0      0      0      0      0      0      0      0]]


In [7]:
# get model accuracy

loss, accuracy = model.evaluate(X_test, encoder(y_test), batch_size=128)

7813/7813 [==============================] - 64s 8ms/step - loss: 0.0442 - accuracy: 0.6810


In [8]:
print("The accuracy of the vanilla RNN model is: {}".format(accuracy))

The accuracy of the vanilla RNN model is: 0.6810399889945984


## Implement the second RNN based on LSTM or GRU neurons in the cell below (10 marks)

In [9]:
# your code here
model_l = Sequential() # create a sequential model

model_l.add(LSTM(units=100, input_shape=(10,1), activation='tanh', return_sequences=True))  # add LSTM neurons to the model
model_l.add(LSTM(units=150, activation='tanh', return_sequences=True))  
model_l.add(LSTM(units=50, activation='tanh'))  

model_l.add(Dense(units=10, activation='tanh')) # add dense layer as the output layer of the model

model_l.compile(loss='mean_squared_error', optimizer='adam', metrics=['accuracy'])
model_l.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 lstm (LSTM)                 (None, 10, 100)           40800     
                                                                 
 lstm_1 (LSTM)               (None, 10, 150)           150600    
                                                                 
 lstm_2 (LSTM)               (None, 50)                40200     
                                                                 
 dense_1 (Dense)             (None, 10)                510       
                                                                 
Total params: 232,110
Trainable params: 232,110
Non-trainable params: 0
_________________________________________________________________


## Train the second RNN based on the training set in the cell below (5 marks)

In [10]:
# your code here
encoder=CategoryEncoding(num_tokens=10, output_mode="one_hot") # one hot coding to vectorize the labels
model_l.fit(X_train, encoder(y_train), epochs=30, batch_size=128, verbose=2)

Epoch 1/30
196/196 - 12s - loss: 0.0575 - accuracy: 0.4934 - 12s/epoch - 62ms/step
Epoch 2/30
196/196 - 8s - loss: 0.0569 - accuracy: 0.5008 - 8s/epoch - 41ms/step
Epoch 3/30
196/196 - 8s - loss: 0.0565 - accuracy: 0.5138 - 8s/epoch - 43ms/step
Epoch 4/30
196/196 - 9s - loss: 0.0559 - accuracy: 0.5356 - 9s/epoch - 44ms/step
Epoch 5/30
196/196 - 9s - loss: 0.0555 - accuracy: 0.5413 - 9s/epoch - 43ms/step
Epoch 6/30
196/196 - 8s - loss: 0.0554 - accuracy: 0.5409 - 8s/epoch - 42ms/step
Epoch 7/30
196/196 - 9s - loss: 0.0554 - accuracy: 0.5413 - 9s/epoch - 45ms/step
Epoch 8/30
196/196 - 9s - loss: 0.0552 - accuracy: 0.5413 - 9s/epoch - 45ms/step
Epoch 9/30
196/196 - 9s - loss: 0.0551 - accuracy: 0.5474 - 9s/epoch - 43ms/step
Epoch 10/30
196/196 - 9s - loss: 0.0551 - accuracy: 0.5455 - 9s/epoch - 43ms/step
Epoch 11/30
196/196 - 9s - loss: 0.0550 - accuracy: 0.5477 - 9s/epoch - 45ms/step
Epoch 12/30
196/196 - 8s - loss: 0.0548 - accuracy: 0.5509 - 8s/epoch - 43ms/step
Epoch 13/30
196/196 - 8

## Evaluate the second RNN based on the testing set in the cell below (5 marks)

In [11]:
# your code here

# get predictions for test data and use argmax to convert output vector to labels

y_pred_l = np.argmax(model_l.predict(X_test), axis=1)

## Present the classification accuracy and confusion matrix of the second RNN in the cell below (10 marks)

In [12]:
# your code here

print(confusion_matrix(y_test, y_pred_l))

[[478199  22971      4     35      0      0      0      0      0      0]
 [ 98376 322285   1155    682      0      0      0      0      0      0]
 [   137  34880  11168   1437      0      0      0      0      0      0]
 [   720   7141    254  13006      0      0      0      0      0      0]
 [  3042    815     14     13      1      0      0      0      0      0]
 [  1878    113      0      5      0      0      0      0      0      0]
 [     0    288    481    655      0      0      0      0      0      0]
 [     0     34      9    187      0      0      0      0      0      0]
 [    11      1      0      0      0      0      0      0      0      0]
 [     2      1      0      0      0      0      0      0      0      0]]


In [13]:
# get model accuracy

loss_l, accuracy_l = model_l.evaluate(X_test, encoder(y_test), batch_size=128)

7813/7813 [==============================] - 128s 16ms/step - loss: 0.0268 - accuracy: 0.8247


In [14]:
print("The accuracy of the LSTM based RNN model is: {}".format(accuracy_l))

The accuracy of the LSTM based RNN model is: 0.824658989906311


## Answer the following question in the cell below  (10 marks).

## Question:
Compare the advantages and disadvantages of the two models you have implemented and give some ideas on how to improve these results/performance further.

Here is a comparison of the advantages and disadvantages of the two models:

1. LSTM provides a much higher accuracy with smaller number of LSTM layers and units compared to simpleRNN.
2. The number of trainable parameters for LSTMs is significantly higher than RNNs.

To improve the models further a number of model hyperparameters can be tuned including activations, weights initialization, optimizers etc. For both LSTMs and RNNs, the number of units and layers can be increased until the loss continues to reduce on a validation split of the data and dropout can be used for LSTM since LSTMs usually overfit the data with a large number of layers. Additionally, the models can be trained for a higher number of epochs. 


## Additional remarks:

Code outline appropriately commented. (10 marks)

Code running without errors. (10 marks)